MODEL_OPENAI="OpenAI"
MODEL_GEMMA3="Gemma3"

CATEGORIES = {'order-modifications': ['item-additions',
  'item-removals',
  'quantity-adjustments',
  'late-modification-requests'],
 'order-cancellations': ['standard-cancellations',
  'urgent-cancellations',
  'rescheduled-orders'],
 'delivery-issues': ['late-deliveries',
  'missed-deliveries',
  'incomplete-deliveries',
  'damaged-goods',
  'delivery-confirmation-issues'],
 'pickup-scheduling-&-rescheduling': ['new-pickup-requests',
  'rescheduling-pickup',
  'missed-pickups',
  'pickup-policy-clarifications'],
 'product-availability-&-substitutions': ['stock-availability-inquiries',
  'out-of-stock-notifications',
  'product-substitution-requests',
  'special-item-requests'],
 'grant-&-billing-issues': ['grant-fund-usage',
  'incorrect-grant-deduction',
  'billing-discrepancies',
  'payment-&-credit-issues'],
 'training-&-account-access': ['training-signups',
  'missed-training-sessions',
  'login-issues',
  'new-user-account-requests'],
 'emergency-situations': ['weather-related-disruptions',
  'personal/organization-emergencies',
  'food-safety-concerns',
  'unexpected-facility-closures'],
 'special-requests': ['educational-materials',
  'large-event-orders',
  'holiday-&-seasonal-adjustments'],
 'technical-support': ['website-&-ordering-system-errors',
  'email-&-communication-issues',
  'data-entry-mistakes',
  'general-it-assistance'],
 'other': ['miscellaneous']}